import { Role, StoreStatus } from '@prisma/client'
import { Router } from 'express'
import { z } from 'zod'
import { config } from '../config.js'
import { prisma } from '../db.js'
import { allowRoles, authenticate } from '../middleware/auth.js'
import { decrypt, encrypt } from '../utils/crypto.js'

export const storesRouter = Router()
storesRouter.use(authenticate)
const storeSchema = z.object({ name: z.string().min(2), address: z.string().min(5), phone: z.string().optional() })
const accessSchema = z.object({ anydeskId: z.string().max(80).optional().nullable(), anydeskPassword: z.string().max(300).optional().nullable(), ofdUrl: z.string().url().optional().nullable(), ofdLogin: z.string().max(200).optional().nullable(), ofdPassword: z.string().max(300).optional().nullable(), nalogUrl: z.string().url().optional().nullable(), nalogLogin: z.string().max(200).optional().nullable(), nalogPassword: z.string().max(300).optional().nullable() })

async function ownStore(id: number, userId: number, isAdmin: boolean) { const store = await prisma.store.findUnique({ where: { id } }); return store && (isAdmin || store.userId === userId) ? store : null }
storesRouter.get('/', async (req, res) => { const isAdmin = req.auth!.role === Role.ADMIN; const stores = await prisma.store.findMany({ where: isAdmin ? {} : { userId: req.auth!.userId }, include: { user: { select: { id: true, ipName: true, phone: true, status: true } }, access: { select: { anydeskId: true, ofdUrl: true, ofdLogin: true, nalogUrl: true, nalogLogin: true, updatedAt: true } }, _count: { select: { requests: true } } }, orderBy: { updatedAt: 'desc' } }); res.json(stores) })
storesRouter.post('/', async (req, res) => { const body = storeSchema.parse(req.body); const admin = req.auth!.role === Role.ADMIN; const ownerId = admin && req.body.userId ? Number(req.body.userId) : req.auth!.userId; res.status(201).json(await prisma.store.create({ data: { ...body, userId: ownerId, status: admin ? StoreStatus.ACTIVE : StoreStatus.PENDING } })) })
storesRouter.patch('/:id', async (req, res) => { const store = await ownStore(Number(req.params.id), req.auth!.userId, req.auth!.role === Role.ADMIN); if (!store) return res.status(404).json({ message: 'Точка не найдена' }); res.json(await prisma.store.update({ where: { id: store.id }, data: storeSchema.partial().parse(req.body) })) })
storesRouter.get('/:id/access', async (req, res) => { const store = await ownStore(Number(req.params.id), req.auth!.userId, req.auth!.role === Role.ADMIN); if (!store) return res.status(404).json({ message: 'Точка не найдена' }); const access = await prisma.storeAccess.findUnique({ where: { storeId: store.id } }); if (!access) return res.json(null); res.json({ ...access, anydeskPassword: access.anydeskPasswordEncrypted && decrypt(access.anydeskPasswordEncrypted, config.encryptionKey), ofdPassword: access.ofdPasswordEncrypted && decrypt(access.ofdPasswordEncrypted, config.encryptionKey), nalogPassword: access.nalogPasswordEncrypted && decrypt(access.nalogPasswordEncrypted, config.encryptionKey), anydeskPasswordEncrypted: undefined, ofdPasswordEncrypted: undefined, nalogPasswordEncrypted: undefined }) })
storesRouter.put('/:id/access', async (req, res) => { const store = await ownStore(Number(req.params.id), req.auth!.userId, req.auth!.role === Role.ADMIN); if (!store) return res.status(404).json({ message: 'Точка не найдена' }); const body = accessSchema.parse(req.body); const data = { anydeskId: body.anydeskId, ofdUrl: body.ofdUrl, ofdLogin: body.ofdLogin, nalogUrl: body.nalogUrl, nalogLogin: body.nalogLogin, ...(body.anydeskPassword !== undefined && { anydeskPasswordEncrypted: body.anydeskPassword ? encrypt(body.anydeskPassword, config.encryptionKey) : null }), ...(body.ofdPassword !== undefined && { ofdPasswordEncrypted: body.ofdPassword ? encrypt(body.ofdPassword, config.encryptionKey) : null }), ...(body.nalogPassword !== undefined && { nalogPasswordEncrypted: body.nalogPassword ? encrypt(body.nalogPassword, config.encryptionKey) : null }), updatedByUserId: req.auth!.userId }; await prisma.storeAccess.upsert({ where: { storeId: store.id }, create: { storeId: store.id, ...data }, update: data }); res.status(204).end() })
storesRouter.post('/:id/approve', allowRoles(Role.ADMIN), async (req, res) => res.json(await prisma.store.update({ where: { id: Number(req.params.id) }, data: { status: StoreStatus.ACTIVE } })))
