import { useCallback, useEffect, useState } from 'react'
import { RefreshCw } from 'lucide-react'
import { api, ApiError } from '../../api'
import { Button, Field } from '../../components/ui'
import type { Component, Stats } from '../../types'

type ProcurementRow = { componentId: number; name: string; quantity: number; requests: number; schedule: Array<{ requestId: number; scheduledAt: string | null; organization: string | null; store: string | null; quantity: number }> }
const errorText = (value: unknown) => value instanceof ApiError || value instanceof Error ? value.message : 'Не удалось загрузить отчёт'
const formatDate = (value?: string | null) => value ? new Intl.DateTimeFormat('ru-RU', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' }).format(new Date(value)) : '—'

export function ReportsPage() {
  const firstDay = () => new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString().slice(0, 10)
  const [from, setFrom] = useState(firstDay), [to, setTo] = useState(() => new Date().toISOString().slice(0, 10))
  const [componentId, setComponentId] = useState(''), [components, setComponents] = useState<Component[]>([]), [procurement, setProcurement] = useState<ProcurementRow[]>([]), [stats, setStats] = useState<Stats | null>(null), [error, setError] = useState(''), [view, setView] = useState<'summary' | 'procurement'>('summary')
  const load = useCallback(async () => { try { setError(''); const query = new URLSearchParams({ from, to }); if (componentId) query.set('componentId', componentId); const [nextStats, nextProcurement] = await Promise.all([api<Stats>(`/requests/stats?from=${from}&to=${to}`), api<ProcurementRow[]>(`/requests/procurement?${query}`)]); setStats(nextStats); setProcurement(nextProcurement) } catch (reason) { setError(errorText(reason)) } }, [from, to, componentId])
  useEffect(() => { void load() }, [load])
  useEffect(() => { void api<Component[]>('/components').then(setComponents).catch(() => setComponents([])) }, [])
  return <>{error && <div className="page-error">{error}</div>}<section className="panel table-panel"><div className="toolbar"><Field label="С"><input type="date" value={from} max={to} onChange={event => setFrom(event.target.value)} /></Field><Field label="По"><input type="date" value={to} min={from} onChange={event => setTo(event.target.value)} /></Field>{view === 'procurement' && <Field label="Компонент"><select value={componentId} onChange={event => setComponentId(event.target.value)}><option value="">Все компоненты</option>{components.filter(component => component.isActive).map(component => <option key={component.id} value={component.id}>{component.name}</option>)}</select></Field>}<Button kind="secondary" onClick={() => void load()}><RefreshCw /> Обновить</Button></div><div className="segmented report-tabs"><button className={view === 'summary' ? 'active' : ''} onClick={() => setView('summary')}>Сводка</button><button className={view === 'procurement' ? 'active' : ''} onClick={() => setView('procurement')}>Планируемые закупки</button></div></section>{view === 'summary' && stats && <div className="stats-grid"><div className="stat-card coral"><div><small>Заявок за период</small><strong>{stats.total}</strong></div></div><div className="stat-card amber"><div><small>Просрочено</small><strong>{stats.overdue}</strong></div></div><div className="stat-card green"><div><small>Выполнено</small><strong>{stats.completed}</strong></div></div><div className="stat-card violet"><div><small>Среднее выполнение</small><strong>{stats.averageResolutionHours} ч</strong></div></div></div>}{view === 'procurement' && <section className="panel table-panel"><div className="panel-head"><div><h2>Планируемые закупки</h2><p>Активные плановые заявки по дате работ в выбранном периоде.</p></div></div>{procurement.length ? <div className="procurement-list">{procurement.map(row => <article key={row.componentId}><div><h3>{row.name}</h3><p>{row.requests} заявок</p></div><strong>{row.quantity} шт.</strong><details><summary>Состав потребности</summary>{row.schedule.map(item => <p key={`${item.requestId}-${item.quantity}`}>#{item.requestId} · {formatDate(item.scheduledAt)} · {item.organization ?? 'Без организации'}{item.store ? ` / ${item.store}` : ''} — {item.quantity} шт.</p>)}</details></article>)}</div> : <p className="report-empty">На выбранный период активных плановых заявок с компонентами нет.</p>}</section>}</>
}
