import { type FormEvent, type ReactNode, useCallback, useEffect, useMemo, useState } from 'react'
import { Activity, AlertTriangle, BarChart3, Bell, Building2, CalendarDays, Check, ChevronRight, Clipboard, ClipboardList, ExternalLink, Eye, EyeOff, FileText, LayoutDashboard, LockKeyhole, LogOut, MapPin, Menu, MonitorUp, Pencil, Plus, RefreshCw, Search, ShieldCheck, Store as StoreIcon, UserPlus, Users, X } from 'lucide-react'
import { api, ApiError, login, logout, restoreSession } from './api'
import bazisLogo from './assets/bazis-logo.svg'
import type { RequestStatus, RequestType, ServiceRequest, Stats, Store, StoreAccess, User, UserStatus } from './types'

const statusLabel: Record<RequestStatus, string> = { NEW: 'Новая', ACCEPTED: 'Принята', IN_PROGRESS: 'В работе', DONE: 'Выполнена', CANCELLED: 'Отменена' }
const userStatusLabel: Record<UserStatus, string> = { PENDING: 'На модерации', ACTIVE: 'Активен', REJECTED: 'Отклонён', BLOCKED: 'Заблокирован' }
const transitions: Record<RequestStatus, RequestStatus[]> = { NEW: ['ACCEPTED', 'CANCELLED'], ACCEPTED: ['IN_PROGRESS', 'CANCELLED'], IN_PROGRESS: ['DONE', 'CANCELLED'], DONE: [], CANCELLED: [] }
const formatDate = (value?: string | null, time = true) => value ? new Intl.DateTimeFormat('ru-RU', { day: '2-digit', month: 'short', year: 'numeric', ...(time && { hour: '2-digit', minute: '2-digit' }) }).format(new Date(value)) : '—'
const errorText = (value: unknown) => value instanceof ApiError || value instanceof Error ? value.message : 'Произошла ошибка'

function Button({ kind = 'primary', children, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { kind?: 'primary' | 'secondary' | 'danger' | 'ghost' }) { return <button className={`button ${kind}`} {...props}>{children}</button> }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="field"><span>{label}</span>{children}</label> }
function Empty({ title, text }: { title: string; text: string }) { return <div className="empty"><ClipboardList /><b>{title}</b><span>{text}</span></div> }
function BrandLogo({ large = false }: { large?: boolean }) { return <div className={`brand ${large ? 'big' : ''}`}><img src={bazisLogo} alt="БАЗИС — Центр технического обслуживания" /></div> }
function Modal({ title, onClose, children, wide }: { title: string; onClose: () => void; children: ReactNode; wide?: boolean }) { return <div className="modal-backdrop" onMouseDown={onClose}><section className={`modal ${wide ? 'wide' : ''}`} onMouseDown={event => event.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">БАЗИС CRM</span><h2>{title}</h2></div><button className="icon-button" onClick={onClose}><X /></button></div>{children}</section></div> }

function AuthView({ onAuth }: { onAuth: (user: User) => void }) {
  const [mode, setMode] = useState<'login' | 'register'>('login'), [busy, setBusy] = useState(false), [error, setError] = useState('')
  const submit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setBusy(true); setError(''); const v = Object.fromEntries(new FormData(event.currentTarget)) as Record<string, string>
    try {
      if (mode === 'register') await api('/auth/register', { method: 'POST', body: JSON.stringify({ ipName: v.ipName, email: v.email, password: v.password, phone: v.phone, store: { name: v.storeName, address: v.address, phone: v.storePhone || undefined } }) }, false)
      onAuth(await login(v.email, v.password))
    } catch (reason) { setError(errorText(reason)) } finally { setBusy(false) }
  }
  return <main className="auth-page"><section className="auth-brand"><BrandLogo large /><div><span className="eyebrow light">ЦЕНТР ТЕХНИЧЕСКОГО ОБСЛУЖИВАНИЯ</span><h1>Заявки, точки и доступы — в одном рабочем пространстве.</h1><p>Быстрая связь между клиентами и сервисным отделом БАЗИС. От срочной заявки до планового обслуживания.</p></div><div className="auth-proof"><span><Check /> Контроль статусов</span><span><Check /> Защищённые доступы</span><span><Check /> Работа с телефона</span></div></section><section className="auth-form-wrap"><form className="auth-form" onSubmit={submit}><h2>{mode === 'login' ? 'Вход в БАЗИС CRM' : 'Регистрация клиента'}</h2><p>{mode === 'login' ? 'Введите данные учётной записи' : 'После регистрации заявку проверит администратор'}</p>{mode === 'register' && <><Field label="Название ИП"><input name="ipName" required minLength={2} placeholder="ИП Иванов" /></Field><div className="form-grid"><Field label="Телефон"><input name="phone" required minLength={5} /></Field><Field label="Название точки"><input name="storeName" required minLength={2} /></Field></div><Field label="Адрес первой точки"><input name="address" required minLength={5} /></Field><Field label="Телефон точки (необязательно)"><input name="storePhone" /></Field></>}<Field label="Email"><input name="email" type="email" autoComplete="email" required /></Field><Field label="Пароль"><input name="password" type="password" autoComplete={mode === 'login' ? 'current-password' : 'new-password'} required minLength={mode === 'register' ? 8 : 1} /></Field>{error && <div className="form-error"><AlertTriangle />{error}</div>}<Button disabled={busy}>{busy ? <RefreshCw className="spin" /> : mode === 'login' ? 'Войти' : 'Отправить на модерацию'}</Button><button type="button" className="auth-switch" onClick={() => { setMode(mode === 'login' ? 'register' : 'login'); setError('') }}>{mode === 'login' ? 'Нет аккаунта? Зарегистрироваться' : 'Уже есть аккаунт? Войти'}</button></form></section></main>
}

function Waiting({ user, exit }: { user: User; exit: () => void }) { const rejected = user.status === 'REJECTED'; return <main className="state-page"><div className={`state-icon ${rejected ? 'rejected' : ''}`}>{rejected ? <X /> : <ShieldCheck />}</div><h1>{rejected ? 'Регистрация отклонена' : 'Регистрация на проверке'}</h1><p>{rejected ? user.rejectionReason || 'Причина не указана.' : 'Администратор проверит данные и активирует личный кабинет.'}</p><b>{user.email}</b><Button kind="secondary" onClick={exit}><LogOut /> Выйти</Button></main> }

function RequestCard({ item, open }: { item: ServiceRequest; open: () => void }) { return <button className="request-card" onClick={open}><div className="request-card-top"><span className="type-chip"><i style={{ background: item.type.color || '#ee7865' }} />{item.type.name}</span><span>#{item.id}</span></div><h3>{item.description}</h3><div className="request-meta"><span><Building2 />{item.createdBy.ipName}</span><span><MapPin />{item.store.name}</span><span><CalendarDays />{formatDate(item.urgency === 'SCHEDULED' ? item.scheduledAt : item.createdAt)}</span></div>{item.adminComment && <p className="comment-preview">Комментарий: {item.adminComment}</p>}<div className="request-card-bottom"><span className={`urgency ${item.urgency.toLowerCase()}`}>{item.urgency === 'URGENT' ? 'Срочная' : 'Плановая'}</span><span className={`status ${item.status.toLowerCase()}`}>{statusLabel[item.status]}</span></div></button> }

function RequestDetails({ item, admin, close, saved, access }: { item: ServiceRequest; admin: boolean; close: () => void; saved: () => void; access: (store: Store) => void }) {
  const [status, setStatus] = useState(item.status), [comment, setComment] = useState(item.adminComment ?? ''), [error, setError] = useState('')
  const save = async () => { try { await api(`/requests/${item.id}`, { method: 'PATCH', body: JSON.stringify({ status, adminComment: comment || null }) }); saved(); close() } catch (reason) { setError(errorText(reason)) } }
  return <Modal title={`Заявка #${item.id}`} onClose={close} wide><div className="detail-grid"><div><small>Тип</small><b>{item.type.name}</b></div><div><small>Срочность</small><b>{item.urgency === 'URGENT' ? 'Срочная' : 'Плановая'}</b></div><div><small>Клиент</small><b>{item.createdBy.ipName}</b><span>{item.createdBy.phone}</span></div><div><small>Точка</small><b>{item.store.name}</b><span>{item.store.address}</span></div><div><small>Создана</small><b>{formatDate(item.createdAt)}</b></div><div><small>Дата работ</small><b>{formatDate(item.scheduledAt)}</b></div></div><div className="description-box"><small>Описание</small><p>{item.description}</p></div>{admin ? <><div className="form-grid"><Field label="Статус"><select value={status} onChange={event => setStatus(event.target.value as RequestStatus)}><option value={item.status}>{statusLabel[item.status]}</option>{transitions[item.status].map(value => <option key={value} value={value}>{statusLabel[value]}</option>)}</select></Field><Field label="Комментарий клиенту"><textarea rows={3} value={comment} onChange={event => setComment(event.target.value)} /></Field></div>{error && <div className="form-error">{error}</div>}<div className="modal-actions"><Button kind="secondary" onClick={() => access(item.store)}><LockKeyhole /> Доступы точки</Button><Button onClick={save}>Сохранить</Button></div></> : item.adminComment ? <div className="admin-comment"><b>Комментарий администратора</b><p>{item.adminComment}</p></div> : null}</Modal>
}

function CreateRequest({ stores, types, close, done }: { stores: Store[]; types: RequestType[]; close: () => void; done: () => void }) {
  const [urgency, setUrgency] = useState<'URGENT' | 'SCHEDULED'>('URGENT'), [error, setError] = useState('')
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const v = Object.fromEntries(new FormData(event.currentTarget)) as Record<string, string>; try { await api('/requests', { method: 'POST', body: JSON.stringify({ storeId: Number(v.storeId), typeId: Number(v.typeId), urgency, scheduledAt: urgency === 'SCHEDULED' ? v.scheduledAt : undefined, description: v.description }) }); done(); close() } catch (reason) { setError(errorText(reason)) } }
  const min = new Date(Date.now() + 300000).toISOString().slice(0, 16), max = new Date(Date.now() + 365 * 86400000).toISOString().slice(0, 16)
  return <Modal title="Новая заявка" onClose={close}><form onSubmit={submit}><Field label="Торговая точка"><select name="storeId" required>{stores.map(store => <option value={store.id} key={store.id}>{store.name} — {store.address}</option>)}</select></Field><Field label="Тип заявки"><select name="typeId" required>{types.filter(type => type.isActive).map(type => <option value={type.id} key={type.id}>{type.name}</option>)}</select></Field><div className="segmented"><button type="button" className={urgency === 'URGENT' ? 'active' : ''} onClick={() => setUrgency('URGENT')}>Срочная</button><button type="button" className={urgency === 'SCHEDULED' ? 'active' : ''} onClick={() => setUrgency('SCHEDULED')}>Запланированная</button></div>{urgency === 'SCHEDULED' && <Field label="Дата и время"><input name="scheduledAt" type="datetime-local" min={min} max={max} required /></Field>}<Field label="Описание"><textarea name="description" rows={5} required minLength={5} /></Field>{!stores.length && <div className="form-error">Нет активных торговых точек</div>}{error && <div className="form-error">{error}</div>}<div className="modal-actions"><Button type="button" kind="secondary" onClick={close}>Отмена</Button><Button disabled={!stores.length}>Отправить</Button></div></form></Modal>
}

function AdminCalendarEvent({ day, stores, types, close, done }: { day: Date; stores: Store[]; types: RequestType[]; close: () => void; done: () => void }) {
  const [error, setError] = useState('')
  const initialDate = new Date(day)
  initialDate.setHours(10, 0, 0, 0)
  if (initialDate.getTime() < Date.now()) initialDate.setTime(Date.now() + 15 * 60000)
  const inputValue = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}T${String(date.getHours()).padStart(2, '0')}:${String(date.getMinutes()).padStart(2, '0')}`
  const submit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setError('')
    const values = Object.fromEntries(new FormData(event.currentTarget)) as Record<string, string>
    try {
      await api('/requests', { method: 'POST', body: JSON.stringify({ storeId: Number(values.storeId), typeId: Number(values.typeId), urgency: 'SCHEDULED', scheduledAt: values.scheduledAt, description: values.description }) })
      done(); close()
    } catch (reason) { setError(errorText(reason)) }
  }
  return <Modal title="Новое событие в календаре" onClose={close}><form onSubmit={submit}><Field label="Торговая точка"><select name="storeId" required>{stores.map(store => <option value={store.id} key={store.id}>{store.user?.ipName} — {store.name}</option>)}</select></Field><Field label="Тип работ"><select name="typeId" required>{types.filter(type => type.isActive).map(type => <option value={type.id} key={type.id}>{type.name}</option>)}</select></Field><Field label="Дата и время"><input name="scheduledAt" type="datetime-local" min={inputValue(new Date())} max={inputValue(new Date(Date.now() + 365 * 86400000))} defaultValue={inputValue(initialDate)} required /></Field><Field label="Описание"><textarea name="description" rows={4} required minLength={5} placeholder="Опишите запланированные работы" /></Field>{!stores.length && <div className="form-error">Нет активных торговых точек</div>}{error && <div className="form-error">{error}</div>}<div className="modal-actions"><Button type="button" kind="secondary" onClick={close}>Отмена</Button><Button disabled={!stores.length || !types.some(type => type.isActive)}>Добавить в календарь</Button></div></form></Modal>
}

function AccessModal({ store, close, saved }: { store: Store; close: () => void; saved: () => void }) {
  const [data, setData] = useState<StoreAccess>({}), [busy, setBusy] = useState(true), [visible, setVisible] = useState<Record<string, boolean>>({}), [message, setMessage] = useState('')
  useEffect(() => { api<StoreAccess | null>(`/stores/${store.id}/access`).then(value => setData(value ?? {})).catch(value => setMessage(errorText(value))).finally(() => setBusy(false)) }, [store.id])
  const copy = async (value?: string | null) => { if (value) { await navigator.clipboard.writeText(value); setMessage('Скопировано') } }
  const secret = (name: keyof StoreAccess, label: string) => <Field label={label}><div className="secret-input"><input name={name} type={visible[name] ? 'text' : 'password'} defaultValue={String(data[name] ?? '')} /><button type="button" onClick={() => setVisible(value => ({ ...value, [name]: !value[name] }))}>{visible[name] ? <EyeOff /> : <Eye />}</button><button type="button" onClick={() => void copy(data[name] as string)}><Clipboard /></button></div></Field>
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); const values = Object.fromEntries(new FormData(event.currentTarget)) as Record<string, string>; try { await api(`/stores/${store.id}/access`, { method: 'PUT', body: JSON.stringify(Object.fromEntries(Object.entries(values).map(([key, value]) => [key, value || null]))) }); setMessage('Доступы сохранены'); saved() } catch (reason) { setMessage(errorText(reason)) } finally { setBusy(false) } }
  return <Modal title={`Доступы · ${store.name}`} onClose={close} wide>{busy ? <div className="loading-line"><RefreshCw className="spin" /> Загрузка защищённых данных…</div> : <form onSubmit={submit}><AccessBlock icon={<MonitorUp />} title="AnyDesk" link={data.anydeskId ? `anydesk:${data.anydeskId}` : undefined}><Field label="AnyDesk ID"><input name="anydeskId" defaultValue={data.anydeskId ?? ''} /></Field>{secret('anydeskPassword', 'Пароль')}</AccessBlock><AccessBlock icon={<ExternalLink />} title="ОФД" link={data.ofdUrl ?? undefined}><Field label="Адрес сайта"><input name="ofdUrl" type="url" defaultValue={data.ofdUrl ?? ''} /></Field><Field label="Логин"><div className="secret-input"><input name="ofdLogin" defaultValue={data.ofdLogin ?? ''} /><button type="button" onClick={() => void copy(data.ofdLogin)}><Clipboard /></button></div></Field>{secret('ofdPassword', 'Пароль')}</AccessBlock><AccessBlock icon={<ShieldCheck />} title="Налоговая" link={data.nalogUrl ?? undefined}><Field label="Адрес сайта"><input name="nalogUrl" type="url" defaultValue={data.nalogUrl ?? ''} /></Field><Field label="Логин"><div className="secret-input"><input name="nalogLogin" defaultValue={data.nalogLogin ?? ''} /><button type="button" onClick={() => void copy(data.nalogLogin)}><Clipboard /></button></div></Field>{secret('nalogPassword', 'Пароль')}</AccessBlock>{message && <div className="inline-message">{message}</div>}<div className="modal-actions"><Button type="button" kind="secondary" onClick={close}>Закрыть</Button><Button disabled={busy}>Сохранить</Button></div></form>}</Modal>
}
function AccessBlock({ icon, title, link, children }: { icon: ReactNode; title: string; link?: string; children: ReactNode }) { return <div className="access-section"><div className="access-title">{icon}<b>{title}</b>{link && <a className="button secondary compact" href={link} target={link.startsWith('http') ? '_blank' : undefined} rel="noreferrer"><ExternalLink /> Открыть</a>}</div><div className="form-grid three">{children}</div></div> }

function StoreForm({ ownerId, store, close, done }: { ownerId?: number; store?: Store; close: () => void; done: () => void }) { const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); await api(store ? `/stores/${store.id}` : '/stores', { method: store ? 'PATCH' : 'POST', body: JSON.stringify({ ...data, ...(ownerId && { userId: ownerId }) }) }); done(); close() }; return <Modal title={store ? 'Редактировать точку' : 'Новая торговая точка'} onClose={close}><form onSubmit={submit}><Field label="Название"><input name="name" required minLength={2} defaultValue={store?.name ?? ''} /></Field><Field label="Адрес"><input name="address" required minLength={5} defaultValue={store?.address ?? ''} /></Field><Field label="Телефон"><input name="phone" defaultValue={store?.phone ?? ''} /></Field><div className="modal-actions"><Button type="button" kind="secondary" onClick={close}>Отмена</Button><Button>Сохранить</Button></div></form></Modal> }

function App() {
  const [user, setUser] = useState<User | null>(null), [booting, setBooting] = useState(true), [page, setPage] = useState('dashboard'), [mobileNav, setMobileNav] = useState(false)
  const [requests, setRequests] = useState<ServiceRequest[]>([]), [stores, setStores] = useState<Store[]>([]), [types, setTypes] = useState<RequestType[]>([]), [clients, setClients] = useState<User[]>([]), [stats, setStats] = useState<Stats | null>(null), [pendingUsers, setPendingUsers] = useState<User[]>([]), [pendingStores, setPendingStores] = useState<Store[]>([])
  const [selected, setSelected] = useState<ServiceRequest | null>(null), [accessStore, setAccessStore] = useState<Store | null>(null), [createRequest, setCreateRequest] = useState(false), [calendarDate, setCalendarDate] = useState<Date | null>(null), [storeForm, setStoreForm] = useState<Store | 'new' | null>(null), [toast, setToast] = useState(''), [loadError, setLoadError] = useState('')
  useEffect(() => { restoreSession().then(setUser).finally(() => setBooting(false)) }, [])
  const notify = useCallback((text: string) => { setToast(text); window.setTimeout(() => setToast(''), 2800) }, [])
  const load = useCallback(async (quiet = false) => { if (!user || user.status !== 'ACTIVE') return; if (!quiet) setLoadError(''); try { const [r, s, t] = await Promise.all([api<ServiceRequest[]>('/requests'), api<Store[]>('/stores'), api<RequestType[]>('/request-types')]); setRequests(r); setStores(s); setTypes(t); if (user.role === 'ADMIN') { const [c, pu, ps, st] = await Promise.all([api<User[]>('/users'), api<User[]>('/moderation/users'), api<Store[]>('/moderation/stores'), api<Stats>('/requests/stats')]); setClients(c); setPendingUsers(pu); setPendingStores(ps); setStats(st) } } catch (reason) { if (!quiet) setLoadError(errorText(reason)) } }, [user])
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(true), 45000); return () => window.clearInterval(timer) }, [load])
  const exit = async () => { await logout(); setUser(null) }
  if (booting) return <div className="boot"><RefreshCw className="spin" /> Загрузка БАЗИС CRM…</div>
  if (!user) return <AuthView onAuth={setUser} />
  if (user.role === 'CLIENT' && user.status !== 'ACTIVE') return <Waiting user={user} exit={exit} />
  const admin = user.role === 'ADMIN', urgent = requests.filter(item => item.urgency === 'URGENT' && !['DONE', 'CANCELLED'].includes(item.status)), scheduled = requests.filter(item => item.urgency === 'SCHEDULED'), activeStores = stores.filter(store => store.status === 'ACTIVE')
  const nav = admin ? [['dashboard', 'Обзор', LayoutDashboard], ['requests', 'Заявки', ClipboardList], ['calendar', 'Календарь', CalendarDays], ['moderation', 'Модерация', ShieldCheck], ['clients', 'Клиенты', Users], ['stores', 'Точки', StoreIcon], ['types', 'Типы заявок', FileText], ['stats', 'Отчёты', BarChart3]] as const : [['dashboard', 'Главная', LayoutDashboard], ['requests', 'Мои заявки', ClipboardList], ['calendar', 'Календарь', CalendarDays], ['stores', 'Мои точки', StoreIcon]] as const
  const titles: Record<string, string> = { dashboard: admin ? 'Рабочий обзор' : 'Личный кабинет', requests: admin ? 'Все заявки' : 'Мои заявки', calendar: 'Календарь работ', moderation: 'Модерация', clients: 'Клиенты', stores: admin ? 'Торговые точки' : 'Мои точки', types: 'Типы заявок', stats: 'Статистика' }
  const go = (value: string) => { setPage(value); setMobileNav(false) }
  return <main className="app-shell"><aside className={`sidebar ${mobileNav ? 'open' : ''}`}><BrandLogo /><div className="workspace"><span>{admin ? 'Б' : user.ipName.charAt(0)}</span><div><small>РАБОЧЕЕ ПРОСТРАНСТВО</small><b>{admin ? 'ЦТО БАЗИС' : user.ipName}</b></div></div><nav>{nav.map(([id, label, Icon]) => <button key={id} className={page === id ? 'active' : ''} onClick={() => go(id)}><Icon /><span>{label}</span>{id === 'requests' && urgent.length > 0 && <em>{urgent.length}</em>}{id === 'moderation' && pendingUsers.length + pendingStores.length > 0 && <em>{pendingUsers.length + pendingStores.length}</em>}</button>)}</nav><div className="sidebar-footer"><span className="avatar">{user.ipName.slice(0, 2).toUpperCase()}</span><div><b>{user.ipName}</b><small>{admin ? 'Администратор' : user.email}</small></div><button onClick={exit}><LogOut /></button></div></aside>{mobileNav && <button className="nav-scrim" onClick={() => setMobileNav(false)} />}
    <section className="content"><header><button className="menu-button" onClick={() => setMobileNav(true)}><Menu /></button><div className="breadcrumb">БАЗИС CRM <ChevronRight /> <b>{titles[page]}</b></div><div className="header-actions"><button onClick={() => void load()}><RefreshCw /></button><button><Bell />{urgent.length > 0 && <i />}</button></div></header><div className="page"><div className="title-row"><div><span className="eyebrow">{new Intl.DateTimeFormat('ru-RU', { weekday: 'long', day: 'numeric', month: 'long' }).format(new Date())}</span><h1>{titles[page]}</h1><p>{admin ? 'Контролируйте обращения клиентов и работу сервиса.' : 'Создавайте заявки и следите за ходом работ.'}</p></div>{!admin && <Button onClick={() => setCreateRequest(true)}><Plus /> Создать заявку</Button>}</div>{loadError && <div className="page-error"><AlertTriangle />{loadError}</div>}
      {page === 'dashboard' && <Dashboard admin={admin} requests={requests} stores={stores} stats={stats} pending={pendingUsers.length + pendingStores.length} open={setSelected} go={go} />}
      {page === 'requests' && <Requests requests={requests} stores={stores} types={types} open={setSelected} />}
      {page === 'calendar' && <Calendar requests={scheduled} admin={admin} open={setSelected} add={setCalendarDate} />}
      {page === 'stores' && <Stores stores={stores} admin={admin} access={setAccessStore} edit={setStoreForm} />}
      {page === 'moderation' && admin && <Moderation users={pendingUsers} stores={pendingStores} done={() => void load()} notify={notify} />}
      {page === 'clients' && admin && <Clients clients={clients} done={() => void load()} notify={notify} />}
      {page === 'types' && admin && <Types types={types} done={() => void load()} notify={notify} />}
      {page === 'stats' && admin && <Reports stats={stats} />}
    </div></section>
    {selected && <RequestDetails item={selected} admin={admin} close={() => setSelected(null)} saved={() => void load()} access={store => { setSelected(null); setAccessStore(store) }} />}{accessStore && <AccessModal store={accessStore} close={() => setAccessStore(null)} saved={() => void load(true)} />}{createRequest && <CreateRequest stores={activeStores} types={types} close={() => setCreateRequest(false)} done={() => { notify('Заявка создана'); void load() }} />}{calendarDate && <AdminCalendarEvent day={calendarDate} stores={activeStores} types={types} close={() => setCalendarDate(null)} done={() => { notify('Событие добавлено в календарь'); void load() }} />}{storeForm && <StoreForm store={storeForm === 'new' ? undefined : storeForm} close={() => setStoreForm(null)} done={() => { notify('Точка сохранена'); void load() }} />}{toast && <div className="toast"><Check />{toast}</div>}
  </main>
}

function Dashboard({ admin, requests, stores, stats, pending, open, go }: { admin: boolean; requests: ServiceRequest[]; stores: Store[]; stats: Stats | null; pending: number; open: (item: ServiceRequest) => void; go: (page: string) => void }) {
  const active = requests.filter(item => !['DONE', 'CANCELLED'].includes(item.status)), urgent = active.filter(item => item.urgency === 'URGENT')
  return <><div className="stats-grid"><Stat icon={<ClipboardList />} tone="coral" label="Активные заявки" value={active.length} /><Stat icon={<Activity />} tone="violet" label="В работе" value={requests.filter(item => item.status === 'IN_PROGRESS').length} /><Stat icon={<Check />} tone="green" label="Выполнено" value={requests.filter(item => item.status === 'DONE').length} /><Stat icon={admin ? <Users /> : <StoreIcon />} tone="amber" label={admin ? 'Активные клиенты' : 'Активные точки'} value={admin ? stats?.activeClients ?? 0 : stores.filter(store => store.status === 'ACTIVE').length} /></div><div className="dashboard-grid"><section className="panel"><div className="panel-head"><div><h2>{admin ? 'Срочные заявки' : 'Последние заявки'}</h2><p>{admin ? 'Требуют внимания в первую очередь' : 'Актуальные обращения по всем точкам'}</p></div><button className="link-button" onClick={() => go('requests')}>Все заявки <ChevronRight /></button></div><div className="card-list">{(admin ? urgent : requests).slice(0, 5).map(item => <RequestCard item={item} open={() => open(item)} key={item.id} />)}{!(admin ? urgent : requests).length && <Empty title="Заявок пока нет" text="Новые обращения появятся здесь" />}</div></section><aside className="side-stack"><section className="panel attention"><span><ShieldCheck /></span><div><h3>{admin ? 'Ожидают модерации' : 'Точки на проверке'}</h3><strong>{admin ? pending : stores.filter(store => store.status === 'PENDING').length}</strong><p>{admin ? 'клиентов и торговых точек' : 'новых торговых точек'}</p><button className="link-button" onClick={() => go(admin ? 'moderation' : 'stores')}>Открыть <ChevronRight /></button></div></section><section className="panel mini-schedule"><div className="panel-head"><div><h2>Ближайшие работы</h2><p>Запланированные заявки</p></div></div>{requests.filter(item => item.urgency === 'SCHEDULED' && item.scheduledAt && new Date(item.scheduledAt) >= new Date()).sort((a, b) => +new Date(a.scheduledAt!) - +new Date(b.scheduledAt!)).slice(0, 4).map(item => <button key={item.id} onClick={() => open(item)}><i style={{ background: item.type.color || '#ee7865' }} /><span><b>{item.type.name}</b><small>{formatDate(item.scheduledAt)} · {item.store.name}</small></span></button>)}</section></aside></div></>
}
function Stat({ icon, tone, label, value }: { icon: ReactNode; tone: string; label: string; value: number }) { return <div className={`stat-card ${tone}`}><span>{icon}</span><div><small>{label}</small><strong>{value}</strong></div></div> }

function Requests({ requests, stores, types, open }: { requests: ServiceRequest[]; stores: Store[]; types: RequestType[]; open: (item: ServiceRequest) => void }) {
  const [search, setSearch] = useState(''), [status, setStatus] = useState(''), [urgency, setUrgency] = useState(''), [store, setStore] = useState(''), [type, setType] = useState('')
  const rows = useMemo(() => requests.filter(item => (!search || `${item.description} ${item.createdBy.ipName} ${item.store.name} ${item.store.address}`.toLowerCase().includes(search.toLowerCase())) && (!status || item.status === status) && (!urgency || item.urgency === urgency) && (!store || item.storeId === Number(store)) && (!type || item.typeId === Number(type))), [requests, search, status, urgency, store, type])
  return <section className="panel table-panel"><div className="toolbar"><div className="search-box"><Search /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Клиент, точка или текст" /></div><select value={status} onChange={event => setStatus(event.target.value)}><option value="">Все статусы</option>{Object.entries(statusLabel).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><select value={urgency} onChange={event => setUrgency(event.target.value)}><option value="">Любая срочность</option><option value="URGENT">Срочные</option><option value="SCHEDULED">Плановые</option></select><select value={store} onChange={event => setStore(event.target.value)}><option value="">Все точки</option>{stores.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select><select value={type} onChange={event => setType(event.target.value)}><option value="">Все типы</option>{types.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></div><div className="request-grid">{rows.map(item => <RequestCard item={item} open={() => open(item)} key={item.id} />)}{!rows.length && <Empty title="Ничего не найдено" text="Измените параметры фильтра" />}</div></section>
}

function Calendar({ requests, admin, open, add }: { requests: ServiceRequest[]; admin: boolean; open: (item: ServiceRequest) => void; add: (day: Date) => void }) {
  const [cursor, setCursor] = useState(new Date()), [view, setView] = useState<'month' | 'week' | 'day'>('month')
  const monthStart = new Date(cursor.getFullYear(), cursor.getMonth(), 1), offset = (monthStart.getDay() + 6) % 7
  const monthDays = Array.from({ length: 42 }, (_, index) => new Date(cursor.getFullYear(), cursor.getMonth(), index - offset + 1))
  const days = view === 'month' ? monthDays : view === 'week' ? Array.from({ length: 7 }, (_, i) => { const d = new Date(cursor); d.setDate(cursor.getDate() - ((cursor.getDay() + 6) % 7) + i); return d }) : [cursor]
  const move = (direction: number) => { const d = new Date(cursor); if (view === 'month') d.setMonth(d.getMonth() + direction); else d.setDate(d.getDate() + direction * (view === 'week' ? 7 : 1)); setCursor(d) }
  return <section className="panel calendar-page"><div className="calendar-toolbar"><div><button onClick={() => setCursor(new Date())}>Сегодня</button><button onClick={() => move(-1)}>‹</button><button onClick={() => move(1)}>›</button><h2>{new Intl.DateTimeFormat('ru-RU', { month: 'long', year: 'numeric', ...(view !== 'month' && { day: 'numeric' }) }).format(cursor)}</h2></div>{admin && <span className="calendar-hint"><Plus /> Нажмите на день, чтобы добавить событие</span>}<div className="segmented small">{([['month', 'Месяц'], ['week', 'Неделя'], ['day', 'День']] as const).map(([value, label]) => <button key={value} className={view === value ? 'active' : ''} onClick={() => setView(value)}>{label}</button>)}</div></div><div className={`calendar-grid ${view}`}>{days.map(day => <div className={`calendar-cell ${admin ? 'clickable' : ''} ${day.getMonth() !== cursor.getMonth() ? 'muted-day' : ''} ${day.toDateString() === new Date().toDateString() ? 'today' : ''}`} key={day.toISOString()} onClick={() => { if (admin) add(day) }}><span>{new Intl.DateTimeFormat('ru-RU', view === 'month' ? { day: 'numeric' } : { weekday: 'short', day: 'numeric' }).format(day)}</span>{requests.filter(item => item.scheduledAt && new Date(item.scheduledAt).toDateString() === day.toDateString()).map(item => <button key={item.id} style={{ borderLeftColor: item.type.color || '#ee7865' }} onClick={event => { event.stopPropagation(); open(item) }}><b>{new Intl.DateTimeFormat('ru-RU', { hour: '2-digit', minute: '2-digit' }).format(new Date(item.scheduledAt!))} · {item.type.name}</b><small>{item.store.name}</small></button>)}</div>)}</div></section>
}

function Stores({ stores, admin, access, edit }: { stores: Store[]; admin: boolean; access: (store: Store) => void; edit: (store: Store | 'new') => void }) {
  const [ownerFilter, setOwnerFilter] = useState('')
  const owners = useMemo(() => Array.from(new Map(stores.filter(store => store.user).map(store => [store.user!.id, store.user!])).values()).sort((a, b) => a.ipName.localeCompare(b.ipName, 'ru')), [stores])
  const visible = admin && ownerFilter ? stores.filter(store => store.user?.id === Number(ownerFilter)) : stores
  const groups = admin ? Array.from(new Map(visible.map(store => [store.user?.id ?? 0, { owner: store.user, stores: [] as Store[] }])).values()) : [{ owner: undefined, stores: [] as Store[] }]
  for (const store of visible) {
    const group = groups.find(item => admin ? item.owner?.id === store.user?.id : true)
    if (group) group.stores.push(store)
  }
  const card = (store: Store) => <article className="store-card" key={store.id}><div className="store-card-head"><span className="store-icon"><StoreIcon /></span><span className={`store-status ${store.status.toLowerCase()}`}>{store.status === 'ACTIVE' ? 'Активна' : store.status === 'PENDING' ? 'На модерации' : 'Отклонена'}</span></div><h3>{store.name}</h3><p><MapPin />{store.address}</p>{store.phone && <p>{store.phone}</p>}{store.rejectionReason && <div className="rejection">Причина: {store.rejectionReason}</div>}<div className="store-metrics"><span><b>{store._count?.requests ?? 0}</b> заявок</span><span><b>{store.access?.anydeskId ? 'Да' : 'Нет'}</b> AnyDesk</span></div><div className="store-actions">{store.access?.anydeskId && <a className="button anydesk-button" href={`anydesk:${store.access.anydeskId.replace(/\s+/g, '')}`} title={`Подключиться к ${store.access.anydeskId}`}><MonitorUp /> Подключиться</a>}<Button kind="secondary" onClick={() => access(store)}><LockKeyhole /> Доступы</Button><Button kind="ghost" onClick={() => edit(store)}><Pencil /></Button></div></article>
  return <><div className="section-actions"><span>{visible.length} из {stores.length} торговых точек</span>{admin ? <label className="owner-filter"><span>Фильтр по ИП</span><select value={ownerFilter} onChange={event => setOwnerFilter(event.target.value)}><option value="">Все ИП</option>{owners.map(owner => <option value={owner.id} key={owner.id}>{owner.ipName}</option>)}</select></label> : <Button onClick={() => edit('new')}><Plus /> Добавить точку</Button>}</div>{groups.map(group => <section className="store-group" key={group.owner?.id ?? 'mine'}>{admin && <div className="store-group-head"><span className="avatar">{group.owner?.ipName.slice(0, 2).toUpperCase()}</span><div><h2>{group.owner?.ipName ?? 'Без владельца'}</h2><p>{group.owner?.phone} · {group.stores.length} точек</p></div></div>}<div className="store-grid">{group.stores.map(card)}</div></section>)}{!visible.length && <Empty title="Торговых точек не найдено" text="Измените фильтр по ИП" />}</>
}

function Moderation({ users, stores, done, notify }: { users: User[]; stores: Store[]; done: () => void; notify: (text: string) => void }) {
  const decide = async (kind: 'users' | 'stores', id: number, status: 'ACTIVE' | 'REJECTED') => { const rejectionReason = status === 'REJECTED' ? window.prompt('Причина отклонения:') : undefined; if (status === 'REJECTED' && !rejectionReason) return; await api(`/moderation/${kind}/${id}`, { method: 'PATCH', body: JSON.stringify({ status, rejectionReason }) }); notify(status === 'ACTIVE' ? 'Одобрено' : 'Отклонено'); done() }
  return <div className="moderation-columns"><ModerationList title="Новые клиенты" empty="Все регистрации обработаны">{users.map(user => <div className="moderation-row" key={user.id}><span className="avatar">{user.ipName.slice(0, 2)}</span><div><b>{user.ipName}</b><span>{user.email} · {user.phone}</span><small>{user.stores?.[0]?.name} · {user.stores?.[0]?.address}</small></div><Decision reject={() => void decide('users', user.id, 'REJECTED')} approve={() => void decide('users', user.id, 'ACTIVE')} /></div>)}</ModerationList><ModerationList title="Новые точки" empty="Все точки обработаны">{stores.map(store => <div className="moderation-row" key={store.id}><span className="avatar"><StoreIcon /></span><div><b>{store.name}</b><span>{store.user?.ipName}</span><small>{store.address}</small></div><Decision reject={() => void decide('stores', store.id, 'REJECTED')} approve={() => void decide('stores', store.id, 'ACTIVE')} /></div>)}</ModerationList></div>
}
function ModerationList({ title, empty, children }: { title: string; empty: string; children: ReactNode }) { const count = Array.isArray(children) ? children.length : children ? 1 : 0; return <section className="panel list-panel"><div className="panel-head"><div><h2>{title}</h2><p>{count} ожидают решения</p></div></div>{count ? children : <Empty title="Новых заявок нет" text={empty} />}</section> }
function Decision({ reject, approve }: { reject: () => void; approve: () => void }) { return <div><Button kind="secondary" onClick={reject}>Отклонить</Button><Button onClick={approve}>Одобрить</Button></div> }

function Clients({ clients, done, notify }: { clients: User[]; done: () => void; notify: (text: string) => void }) {
  const [create, setCreate] = useState(false), [search, setSearch] = useState(''), [storeOwner, setStoreOwner] = useState<User | null>(null)
  const change = async (client: User, status: UserStatus) => { const rejectionReason = status === 'REJECTED' ? window.prompt('Причина отклонения:') : undefined; if (status === 'REJECTED' && !rejectionReason) return; await api(`/users/${client.id}/status`, { method: 'PATCH', body: JSON.stringify({ status, rejectionReason }) }); notify('Статус обновлён'); done() }
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const v = Object.fromEntries(new FormData(event.currentTarget)) as Record<string, string>; await api('/users', { method: 'POST', body: JSON.stringify({ ipName: v.ipName, email: v.email, phone: v.phone, password: v.password, store: { name: v.storeName, address: v.address, phone: v.storePhone || undefined } }) }); setCreate(false); notify('Клиент создан'); done() }
  const rows = clients.filter(client => `${client.ipName} ${client.email} ${client.phone}`.toLowerCase().includes(search.toLowerCase()))
  return <><div className="section-actions"><div className="search-box"><Search /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Найти клиента" /></div><Button onClick={() => setCreate(true)}><UserPlus /> Добавить клиента</Button></div><section className="panel data-table"><div className="table-row table-head"><span>Клиент</span><span>Контакты</span><span>Точки</span><span>Заявки</span><span>Статус</span><span /></div>{rows.map(client => <div className="table-row" key={client.id}><span><b>{client.ipName}</b><small>с {formatDate(client.createdAt, false)}</small></span><span>{client.email}<small>{client.phone}</small></span><span>{client.stores?.length ?? 0}</span><span>{client._count?.createdRequests ?? 0}</span><span className={`store-status ${client.status.toLowerCase()}`}>{userStatusLabel[client.status]}</span><span className="client-actions"><select value={client.status} onChange={event => void change(client, event.target.value as UserStatus)}><option value="ACTIVE">Активен</option><option value="BLOCKED">Заблокирован</option><option value="REJECTED">Отклонён</option></select><Button kind="ghost" title="Добавить точку" onClick={() => setStoreOwner(client)}><Plus /></Button></span></div>)}</section>{create && <Modal title="Новый клиент" onClose={() => setCreate(false)}><form onSubmit={submit}><div className="form-grid"><Field label="Название ИП"><input name="ipName" required minLength={2} /></Field><Field label="Телефон"><input name="phone" required minLength={5} /></Field></div><Field label="Email"><input name="email" type="email" required /></Field><Field label="Временный пароль"><input name="password" type="text" required minLength={8} /></Field><div className="form-grid"><Field label="Название точки"><input name="storeName" required minLength={2} /></Field><Field label="Телефон точки"><input name="storePhone" /></Field></div><Field label="Адрес точки"><input name="address" required minLength={5} /></Field><div className="modal-actions"><Button type="button" kind="secondary" onClick={() => setCreate(false)}>Отмена</Button><Button>Создать</Button></div></form></Modal>}{storeOwner && <StoreForm ownerId={storeOwner.id} close={() => setStoreOwner(null)} done={() => { notify(`Точка для ${storeOwner.ipName} создана`); done() }} />}</>
}

function Types({ types, done, notify }: { types: RequestType[]; done: () => void; notify: (text: string) => void }) {
  const [editing, setEditing] = useState<RequestType | 'new' | null>(null)
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); await api(editing === 'new' ? '/request-types' : `/request-types/${(editing as RequestType).id}`, { method: editing === 'new' ? 'POST' : 'PATCH', body: JSON.stringify(data) }); setEditing(null); notify('Тип сохранён'); done() }
  const toggle = async (type: RequestType) => { await api(`/request-types/${type.id}`, { method: 'PATCH', body: JSON.stringify({ isActive: !type.isActive }) }); done() }
  return <><div className="section-actions"><span>{types.filter(type => type.isActive).length} активных типов</span><Button onClick={() => setEditing('new')}><Plus /> Добавить тип</Button></div><div className="type-grid">{types.map(type => <article className={`type-card ${type.isActive ? '' : 'inactive'}`} key={type.id}><i style={{ background: type.color || '#ee7865' }} /><div><h3>{type.name}</h3><p>{type.description || 'Без описания'}</p><span>{type.isActive ? 'Активен' : 'Отключён'}</span></div><div><Button kind="ghost" onClick={() => setEditing(type)}><Pencil /></Button><Button kind="secondary" onClick={() => void toggle(type)}>{type.isActive ? 'Отключить' : 'Включить'}</Button></div></article>)}</div>{editing && <Modal title={editing === 'new' ? 'Новый тип заявки' : 'Редактирование типа'} onClose={() => setEditing(null)}><form onSubmit={submit}><Field label="Название"><input name="name" required minLength={2} defaultValue={editing === 'new' ? '' : editing.name} /></Field><Field label="Описание"><textarea name="description" rows={3} defaultValue={editing === 'new' ? '' : editing.description ?? ''} /></Field><Field label="Цвет"><input name="color" type="color" defaultValue={editing === 'new' ? '#ee7865' : editing.color ?? '#ee7865'} /></Field><div className="modal-actions"><Button type="button" kind="secondary" onClick={() => setEditing(null)}>Отмена</Button><Button>Сохранить</Button></div></form></Modal>}</>
}

function Reports({ stats }: { stats: Stats | null }) { if (!stats) return <Empty title="Нет данных" text="Статистика появится после загрузки" />; const max = Math.max(1, ...stats.byType.map(item => item._count._all)); return <><div className="stats-grid"><Stat icon={<ClipboardList />} tone="coral" label="Всего за месяц" value={stats.total} /><Stat icon={<AlertTriangle />} tone="amber" label="Срочных" value={stats.urgent} /><Stat icon={<Users />} tone="green" label="Активных клиентов" value={stats.activeClients} /><Stat icon={<Activity />} tone="violet" label="В работе" value={stats.byStatus.find(item => item.status === 'IN_PROGRESS')?._count._all ?? 0} /></div><div className="report-grid"><section className="panel chart-panel"><div className="panel-head"><div><h2>Заявки по типам</h2><p>Текущий календарный месяц</p></div></div><div className="bar-chart">{stats.byType.map(item => <div key={item.typeId}><span>{item.type?.name ?? `Тип #${item.typeId}`}</span><div><i style={{ width: `${item._count._all / max * 100}%`, background: item.type?.color || '#ee7865' }} /></div><b>{item._count._all}</b></div>)}</div></section><section className="panel chart-panel"><div className="panel-head"><div><h2>По статусам</h2><p>Распределение заявок</p></div></div><div className="status-summary">{stats.byStatus.map(item => <div key={item.status}><span className={`status ${item.status.toLowerCase()}`}>{statusLabel[item.status]}</span><b>{item._count._all}</b></div>)}</div></section></div></> }

export default App
